pageinfo = [[1542182474,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182474,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182474,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182474,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182474,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182474,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182472,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null],
	[1542182473,0,0,0,null]];
pagedata = [ ["./abmeldungen.html","Abmeldungen","Thema: Abmeldungen  Ansprechpartner und Adressaten: Jugendvorstand Trainer  Vorgehen: Wechselwilligen Jugendspielern, die sich nach der ...",""],
["./anmeldungen.html","Anmeldungen","Thema: Anmeldungen  Ansprechpartner und Adressaten: Jugendvorstand Geschäftsstelle: Robert Macioszek, Sensenfeld 96, 46244 Bottrop Telefon: (...",""],
["./ansprechpartner-fussballkreis.html","Ansprechpartner Fussballkreis 2018-2019","ACHTUNG: die flvw.evpost.de-Mailadressen sind nur über das  DFB-Postfach zu erreichen!!!",""],
["./antrag-1000-x-1000-fuer-projek.html","Antrag 1000 x 1000 für Projekte in Kitas und offenem Ganztag","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./ausbildung---fortbildung---leh.html","Ausbildung - Fortbildung - Lehrgänge","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./ausstattung---sportmaterial.html","Ausstattung - Sportmaterial","Thema: Ausstattung, Sportmaterial (Neuanschaffungen, Ersatzanschaffungen)  Ansprechpartner und Adressaten: Ulrich Spickenbaum Christiane Fres...",""],
["./chapter-2.html","VfL Grafenwald-Jugend-Ausstattung","Die Jugendabteilung des VfL Grafenwald wird ab der Saison 2017/2018 einheitlich ausgestattet.",""],
["./dfbnet.html","DFBnet","Thema: DFBnet-Zugang  Ansprechpartner und Adressaten: Ansprechpartner: Administratoren (aktuell Dirk Schlüsener, Birgitt Schuknecht) Adressat...",""],
["./durchfuehrungsbestimmungen-201.html","Durchführungsbestimmungen","Hier die aktuellen  Durchführungsbestimmungen des Fußball- und Leichtathletik-Verbandes Westfalen e.V. für die Saison 2018/2019",""],
["./ehrenamt.html","Ehrenamt","Thema: Ehrenamtspreise: Diese Preise werden jährlich vergeben. Die Vereine liefern einen Vorschlag pro Jahr und Auszeichnung. Die Auswahl trifft d...",""],
["./einladung-zu-jugendvorstandssi.html","Einladung zu Jugendvorstandssitzungen","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./einladung-zum-jugendtag.html","Einladung zum Jugendtag","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./elektronisches-postfach.html","Elektronisches Postfach","Thema: Elektronisches Postfach  Ansprechpartner und Adressaten: Mitarbeiter im Senioren- und Jugendbereich  Vorgehen: Das elektronische ...",""],
["./erweitertes-fuehrungszeugnis.html","Erweitertes Führungszeugnis","Thema: Erweitertes Führungszeugnis / Verhaltenskodex Für jeden, der Umgang mit Kindern in unserem Verein hat, gelten Regeln. Neben der Unterzeichu...",""],
["./externes-catering---feuerwehrf.html","Externes Catering - Feuerwehrfest - 2K2G","Thema: externes Catering - Feuerwehrfest (jährlich) und 2K2G-Karneval (alle zwei Jahre, ungerade)   Ansprechpartner und Adressaten: Jugendvor...",""],
["./freundschaftsspiele.html","Spielanträge und Spielverlegungen","Thema: Spielanträge, Spielverlegungen  Ansprechpartner und Adressaten: Sportwart: Norbert Moß Vfl-Trainer  Vorgehen: Spielanträge und Ve...",""],
["./generalschluessel.html","Generalschlüssel","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./hallenbuchung-fuer-training-un.html","Hallenbuchung für Training und Turniere","Thema: Training und Turniere in der Halle    Ansprechpartner und Adressaten: Jugendvorstand    Vorgehen: Wer in der Halle trai...",""],
["./index.html","VfL Grafenwald-Jugend - Willkommen","Herzlich willkommen beim VfL Grafenwald! Dieses \"VfL-Wiki\" soll uns helfen, die internen Abläufe und Zuständigkeiten innerhalb unserer F...",""],
["./interne-ablaeufe.html","Interne Abläufe","Die nachfolgenden Seiten sollen die internen Abläufe sowie Zuständigkeiten innerhalb der VfL-Jugend beschreiben.",""],
["./internet-administration.html","Internet-Administration","Unser Internet-Auftritt wird z.Z. von Klaus Sievers betreut.",""],
["./internet.html","Internet","Thema: Internet - Homepage  Ansprechpartner und Adressaten: Klaus Sievers Michael Schlautmann  Vorgehen: Klaus Sievers ist Internet-Admi...",""],
["./jugendkassierer.html","Jugendkassierer","Buchführung für die Fußballjugend (Zeitaufwand ca. 2-3 Stunden mtl.)",""],
["./kinderschutz---unbequeme-frage.html","Kinderschutz - unbequeme Fragen - konkrete Antworten","HIER gibt es kurze und zusammengefasste Antworten auf häufig gestellte Fragen zum Thema &#8222;Kinderschutz im Verein&#8220;.",""],
["./kinderschutz---verhaltenskodex.html","Kinderschutz - Verhaltenskodex des VfL","Für alle Mitglieder unseres Vereins und diejenigen, die für den Verein tätig sind, gelten die folgenden Regeln im Umgang mit Kindern und Jugendlic...",""],
["./kinderschutz---warum-tun-wir-d.html","Kinderschutz - warum tun wir das?","&#8222;Warum tun wir das?&#8220; Ein Verein, der ohne konkreten Anlass das Thema Kinderschutz aufgreift, sollte deutlich machen, warum er das tut. Der Einwand...",""],
["./kinderschutz.html","Kinder- und Jugendschutz","Thema: Kinder- und Jugendschutz beim VfL Grafenwald, wir nehmen unsere Verantwortung wahr.  Ansprechpartner und Adressaten: Es gibt 2 Kinders...",""],
["./kontaktdaten.html","Kontaktdaten","Thema: Kontaktdatenbank  Ansprechpartner und Adressaten: Ansprechpartner: Birgitt Schuknecht Adressat/en: Mitarbeiter der Abteilung Fußball (...",""],
["./kontakte.html","Kontakte","Mannschaft / Funktion Name Funktion Telefon privat Telefon mobil Telefon dienstlich E-Mail 1 E-Mail 2         Stand 2018-09-01...",""],
["./kunstrasenbewaesserung.html","Kunstrasenbewässerung","Thema: Kunstrasenbewässerung  Ansprechpartner und Adressaten: jeder Trainer  Vorgehen: Der Kunstrasen hat eine Bewässerungsanlage. Ein S...",""],
["./leitmotive-der-fussball-jugend.html","Leitmotive der Fussball-Jugend","Thema: Leitmotive der Fußball-Jugend  Ansprechpartner und Adressaten: Jugendvorstand (Birgitt Schuknecht/Michael Schlautmann)  Vorgehen:...",""],
["./literatur---fussballtraining.html","Literatur - Fussballtraining","Thema: Literatur, die Fussball-Jugend hat Zeitschriften abonniert  Ansprechpartner und Adressaten: Michael Schlautmann   Vorgehen: Die F...",""],
["./meldung-von-mannschaften.html","Meldung von Mannschaften","Thema: Meldung/Zurückziehen von Mannschaften im DFBnet  Ansprechpartner und Adressaten: Sportwart  Vorgehen: Zu Beginn einer Saison müss...",""],
["./mieten-des-vereinsheims.html","Mieten des Vereinsheims","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./mitarbeitergewinnung.html","Mitarbeitergewinnung","Thema: Mitarbeitergewinnung  Ansprechpartner und Adressaten: Jugendvorstand Seniorenvorstand  Vorgehen: Die Fußballabteilung sucht Mitar...",""],
["./nutzung-der-sportanlage-fuer-n.html","Nutzung der Sportanlage für nichtsportliche Aktivitäten","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./overview.html","JAKO-Flyer VfL Grafenwald","Contents Index Search ",""],
["./platzbelegungen_-trainingszeit.html","Platzbelegungen, Trainingszeiten","Thema: Trainingszeiten, Platzbelegung  Ansprechpartner und Adressaten: Birgitt Schuknecht Norbert Moß Uwe Bromkamp  Vorgehen: Am Anfang ...",""],
["./probetraining---erlaubnisbesch.html","Probetraining - Erlaubnisbescheinigung","Thema: Probetraining - Erlaubnisbescheinigung  Ansprechpartner und Adressaten: Der betroffene Spieler / die Erziehungsberechtigten des Spiele...",""],
["./regeln-ferienfreizeiten-und-tr.html","Regeln Ferienfreizeiten und Trainingslager","Unter dem Aspekt der Prävention von sexualisierter Gewalt im Fußball sollten Vereine bei mehrtägigen Veranstaltungen, wie Trainingslagern oder Fer...",""],
["./regularien-und-ansprechpartner.html","Regularien und Ansprechpartner bei erforderlichen Platzsperren","Thema: Platzsperren  Ansprechpartner und Adressaten: Platzwart Norbert Moß Sport- und Bäderamt Bottrop  Vorgehen: Grundsätzlich werden b...",""],
["./satzung---jugendordnung.html","Jugendordnung","Thema: Jugendordnung  Ansprechpartner und Adressaten: Jugendvorstand (nicht die Fussballjugend) Präsidium  Vorgehen:     § 1Na...",""],
["./satzung-des-vfl-grafenwald.html","Satzung des VfL Grafenwald","Thema: Satzung des VfL Grafenwald  Ansprechpartner und Adressaten: Präsidium  Vorgehen: Die Vereinssatzung des VfL Grafenwald kann HIER ...",""],
["./schiedsrichter.html","Schiedsrichter","Thema: Schiedsrichter beim VfL  Ansprechpartner und Adressaten: Seniorenvorstand Volker Schalt (Schiedsrichter-Obmann)  Vorgehen: Der Sc...",""],
["./schiedsrichtergeld.html","Schiedsrichtergeld - Erstattung von Auslagen","Thema: Schiedsrichtergeld - Erstattung von Auslagen (Erste Hilfe Materialien, Trainingsmaterial, ...)  Ansprechpartner und Adressaten: Jugend...",""],
["./sonderurlaub---woeller-fussbal.html","Sonderurlaub - Wöller Fussballcamp","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./spenden---spendenbescheinigung.html","Spenden - Spendenbescheinigung","Thema: Spende - Spendenquittung  Ansprechpartner und Adressaten: Christiane Frese Geschäftsstelle: Robert Macioszek, Sensenfeld 96, 46244 Bot...",""],
["./sponsoring.html","Sponsoring","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./sportunfaelle.html","Sportunfälle","Thema: Unsere Mitglieder sind über die Sporthilfe versichert. Diese springt ein, wenn die Versicherung des Mitglieds Leistungen nicht erbringt ode...",""],
["./teilhabe-antraege.html","Teilhabe-Anträge","Thema: Teilhabe-Anträge, Bildungspaket  Ansprechpartner und Adressaten: Christiane Frese Stadt Bottrop  Vorgehen: Familien, die Leistung...",""],
["./tombolas-und-ausspielungen.html","Tombolas und Ausspielungen","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./vereinswechsel-innerhalb-der-s.html","Vereinswechsel innerhalb der Saison","Thema: Vereinswechsel innerhalb der Saison  Ansprechpartner und Adressaten: Der betroffene Jugendspieler bzw. die Erziehungsberechtigen Der T...",""],
["./veroeffentlichungen.html","Veröffentlichungen","Thema:   Ansprechpartner und Adressaten:   Vorgehen:",""],
["./vfl-jugend-organigramm.html","VfL-Jugend Organigramm","HIER findet man ein Organigramm der Fussball-Jugend des VfL Grafenwald im PDF-Format",""],
["./vorlage-ablauf.html","Vorlage Ablauf","Thema: aaaa  Ansprechpartner und Adressaten: bbbb  Vorgehen: cccc",""],
["./vorzeitige-seniorenerklaerung.html","Vorzeitige Seniorenerklärung","Thema: Vorzeitige Seniorenerklärung  Ansprechpartner und Adressaten: Der betroffene Spieler Der Trainer des betroffenen Spielers Der Senioren...",""],
["./waldgefluester---90-minuten.html","Waldgeflüster - 90-Minuten","Thema: Waldgeflüster - 90-Minuten  Ansprechpartner und Adressaten: Uwe Bromkamp Birgitt Schuknecht Elias Schlautmann  Vorgehen: Das &#38;quo...",""],
["./zuschuesse-fuer-jugendfreizeit.html","Zuschüsse für Jugendfreizeiten/Mannschaftsfahrten","Thema: Zuschüsse für Jugendfreizeiten/Mannschaftsfahrten/Sonstiges  Ansprechpartner und Adressaten: Christiane Frese Nadine Rosrodowski &#38;nbsp...",""]];
