hmLoadTopic({
hmKeywords:"",
hmTitle:"Ehrenamt",
hmDescription:"Thema: Ehrenamtspreise: Diese Preise werden jährlich vergeben. Die Vereine liefern einen Vorschlag pro Jahr und Auszeichnung. Die Auswahl trifft der Kreis 12.  Ansprechpartner u",
hmPrevLink:"zuschuesse-fuer-jugendfreizeit.html",
hmNextLink:"internet.html",
hmParentLink:"interne-ablaeufe.html",
hmBreadCrumbs:"<a href=\"interne-ablaeufe.html\">Interne Abläufe<\/a>",
hmTitlePath:"Interne Abläufe > Ehrenamt",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Ehrenamt<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Thema:<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">Ehrenamtspreise: Diese Preise werden jährlich vergeben. Die Vereine liefern einen Vorschlag pro Jahr und Auszeichnung. Die Auswahl trifft der Kreis 12.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Ansprechpartner und Adressaten:<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">Abteilungsvorstand Fußball<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">Vorstand Fußballjugend<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Vorgehen:<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">Abgabe der Bewerbung ist jeweils der 30. September, Empfänger ist der Kreisehrenamtsbeauftragte. Anträge und Informationen gibt es beim Fußballkreis 12 (http:\/\/<a href=\"http:\/\/www.flvw-kreis-12.net\/ehrungen.html\" target=\"_blank\" class=\"weblink\">http:\/\/www.flvw-kreis-12.net\/ehrungen.html<\/a>) und in der Vorstandscloud.<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">1. Die Vorstände der Fußballabteilung erstellen gemäß den Vorgaben für die Bewerbung eine Kandidatenliste für<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">a) den DFB-Ehrenamtspreis<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">b) den Fußballhelden (Aktion Junges Ehrenamt); infrage kommen generell nur Kandidaten im Alter von 16 bis 30 Jahren<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">2. Die Vorstände der Fußballabteilung formulieren die Bewerbung und reichen sie beim Ehrenamtsbeauftragten ein.<\/span><\/p>\n\r<p class=\"p_ARIAL11\" style=\"margin: 0px 0.3125rem 0px 0px;\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r"
})
