hmLoadTopic({
hmKeywords:"",
hmTitle:"Spielanträge und Spielverlegungen",
hmDescription:"Thema: Spielanträge, Spielverlegungen  Ansprechpartner und Adressaten: Sportwart: Norbert Moß Vfl-Trainer  Vorgehen: Spielanträge und Verlegungen von Heimspielen organisier",
hmPrevLink:"meldung-von-mannschaften.html",
hmNextLink:"regularien-und-ansprechpartner.html",
hmParentLink:"interne-ablaeufe.html",
hmBreadCrumbs:"<a href=\"interne-ablaeufe.html\">Interne Abläufe<\/a>",
hmTitlePath:"Interne Abläufe > Spielanträge und Spielverlegungen",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Spielanträge und Spielverlegungen<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"margin: 0px 14.2500rem 0px 0px;\"><span style=\"font-weight: bold; text-decoration: underline;\">Thema:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Spielanträge, Spielverlegungen<\/span><\/p>\n\r<p style=\"margin: 0px 14.2500rem 0px 0px;\"><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 14.2500rem 0px 0px;\"><span style=\"font-weight: bold; text-decoration: underline;\">Ansprechpartner und Adressaten:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Sportwart: Norbert Moß<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Vfl-Trainer<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0px 14.2500rem 0px 0px;\"><span style=\"font-weight: bold; text-decoration: underline;\">Vorgehen:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Spielanträge und Verlegungen von Heimspielen organisiert der Sportwart, Norbert Moß, in Abstimmung mit allen beteiligten Mannschaften\/Trainern. Anträge für Freundschaftsspiele und Verlegungen sind im DFBnet bzw. über das E-Postfach zu beantragen.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Bei Verlegungen von Auswärtsspielen ist es geboten, dass sich der VfL-Trainer zunächst mit dem gegenerischen Trainer auf einen neuen Ausweichtermin einigt.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Ist ein Ausweichtermin gefunden, dann bitte Info an den Sportwart, Norbert Moß, sodass dieser die Verlegung im DFBnet offiziell beantragen kann. Es besteht auch die Möglichkeit, dass der gegnerische Sportwart die Verlegung von sich aus beantragt - bitte erfragen!<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r"
})
