hmLoadTopic({
hmKeywords:"",
hmTitle:"Internet",
hmDescription:"Thema: Internet - Homepage  Ansprechpartner und Adressaten: Klaus Sievers Michael Schlautmann  Vorgehen: Klaus Sievers ist Internet-Administrator und verwaltet unsere Homep",
hmPrevLink:"ehrenamt.html",
hmNextLink:"waldgefluester---90-minuten.html",
hmParentLink:"interne-ablaeufe.html",
hmBreadCrumbs:"<a href=\"interne-ablaeufe.html\">Interne Abläufe<\/a>",
hmTitlePath:"Interne Abläufe > Internet",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Internet<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\" style=\"font-size: 1.09rem; font-weight: bold; text-decoration: underline;\">Thema:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Internet - Homepage<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\" style=\"font-size: 1.09rem; font-weight: bold; text-decoration: underline;\">Ansprechpartner und Adressaten:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Klaus Sievers<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Michael Schlautmann<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\" style=\"font-size: 1.09rem; font-weight: bold; text-decoration: underline;\">Vorgehen:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\"><a href=\"mailto:sievers.klaus@gmx.de\" class=\"weblink\">Klaus Sievers<\/a> ist Internet-Administrator und verwaltet unsere <a href=\"http:\/\/vfl-grafenwald-jugend.de\/#\/\" target=\"_blank\" class=\"weblink\">Homepage<\/a><\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Jede Mannschaft besitzt einen Benutzerzugang mit Benutzername und Kennwort (bitte vertraulich behandeln).<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Jede Mannschaft (das muss nicht der Trainer sein, kann auch ein Elternteil sein) kann und sollte hier die Mannschaftsseite mit Leben füllen. Es können &quot;News&quot; eingetragen werden, Bilder hochgeladen werden oder auch &quot;Verlinkungen&quot; (z.B. nach <a href=\"http:\/\/www.fussball.de\/verein\/vfl-grafenwald-westfalen\/-\/id\/00ES8GN8OC000023VV0AG08LVUPGND5I#!\/section\/stage\" target=\"_blank\" class=\"weblink\">Fussball.de<\/a>) definiert werden. Ebenso können alte News gelöscht oder bearbeitet werden.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Bei allen Eintragungen gilt: <\/span><span class=\"f_ARIAL11\" style=\"font-weight: bold;\">&quot;Fair Play, bitte niemanden beleidigen oder den Gegner schlecht reden...&quot;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Bitte davon rege Gebrauch machen, unsere Außendarstellung ist wichtig.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Bei Fragen oder Anregungen bitte <a href=\"mailto:sievers.klaus@gmx.de\" class=\"weblink\">Klaus Sievers<\/a> direkt kontaktieren<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r"
})
