hmLoadTopic({
hmKeywords:"",
hmTitle:"Kontaktdaten",
hmDescription:"Thema: Kontaktdatenbank  Ansprechpartner und Adressaten: Ansprechpartner: Birgitt Schuknecht Adressat\/en: Mitarbeiter der Abteilung Fußball (Trainer, Betreuer, Vorstände Jugen",
hmPrevLink:"satzung---jugendordnung.html",
hmNextLink:"mitarbeitergewinnung.html",
hmParentLink:"interne-ablaeufe.html",
hmBreadCrumbs:"<a href=\"interne-ablaeufe.html\">Interne Abläufe<\/a>",
hmTitlePath:"Interne Abläufe > Kontaktdaten",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Kontaktdaten<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Thema:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Kontaktdatenbank<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Ansprechpartner und Adressaten:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Ansprechpartner: Birgitt Schuknecht<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Adressat\/en: Mitarbeiter der Abteilung Fußball (Trainer, Betreuer, Vorstände Jugend und Senioren), Präsidium, Abteilungsvorstände<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Vorgehen:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Die Kontaktdatenbank wird laufend aktualisiert.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Birgitt Schuknecht ist über Änderung relevanter Daten (auch über zu löschende Daten) zu informieren.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Die Datei ist vertraulich zu behandeln und steht nur dem genannten Adressaten zur Verfügung.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Jeder Mitarbeiter entscheidet, welche Daten er in der Datei veröffentlicht sehen möchte. Diese Entscheidung kann er jederzeit neu vornehmen.<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r"
})
