hmLoadTopic({
hmKeywords:"",
hmTitle:"Mitarbeitergewinnung \/ offene Stellen",
hmDescription:"Thema: Mitarbeitergewinnung  Ansprechpartner und Adressaten: Jugendvorstand Seniorenvorstand  Vorgehen: Die Fußballabteilung sucht Mitarbeiter für die folgenden Aufgabengeb",
hmPrevLink:"kontaktdaten.html",
hmNextLink:"internet-administration.html",
hmParentLink:"interne-ablaeufe.html",
hmBreadCrumbs:"<a href=\"interne-ablaeufe.html\">Interne Abläufe<\/a>",
hmTitlePath:"Interne Abläufe > Mitarbeitergewinnung",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Mitarbeitergewinnung \/ offene Stellen<\/span><\/h1>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r",
hmBody:"<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Thema:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Mitarbeitergewinnung<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Ansprechpartner und Adressaten:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Jugendvorstand<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Seniorenvorstand<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Comment\" style=\"text-align: left;\"><span class=\"f_Comment\" style=\"font-size: 1.09rem; font-family: Arial,Helvetica,sans-serif; font-weight: bold; text-decoration: underline;\">Vorgehen:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Die Fußballabteilung sucht Mitarbeiter für die folgenden Aufgabengebiete:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\"><a href=\"internet-administration.html\" class=\"topiclink\">Internet<\/a>: zur Unterstützung von Klaus Sievers<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Zeugwart: führt die Inventurlisten (Trikots und Trainingsmaterial), nimmt die (Ersatz-)Bestellungen der Mannschaften entgegen, organisiert Aufräumaktionen<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">&nbsp;<\/span><\/p>\n\r"
})
