hmLoadTopic({
hmKeywords:"",
hmTitle:"Sportunfälle",
hmDescription:"Thema: Unsere Mitglieder sind über die Sporthilfe versichert. Diese springt ein, wenn die Versicherung des Mitglieds Leistungen nicht erbringt oder es langfristige Folgeschäden...",
hmPrevLink:"elektronisches-postfach.html",
hmNextLink:"platzbelegungen_-trainingszeit.html",
hmParentLink:"interne-ablaeufe.html",
hmBreadCrumbs:"<a href=\"interne-ablaeufe.html\">Interne Abläufe<\/a>",
hmTitlePath:"Interne Abläufe > Sportunfälle",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Sportunfälle<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\"><span style=\"font-weight: bold; text-decoration: underline;\">Thema:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">Unsere Mitglieder sind über die Sporthilfe versichert. Diese springt ein, wenn die Versicherung des Mitglieds Leistungen nicht erbringt oder es langfristige Folgeschäden gibt. Die Abstimmung erfolgt zwischen der Versicherung des Mitglieds und der Sporthilfe.<\/span><\/p>\n\r<p><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold; text-decoration: underline;\">Ansprechpartner und Adressaten:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">1. Jugendleitung (Unfall melden)<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">2. Geschäftsstelle (Formular einreichen)<\/span><\/p>\n\r<p><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold; text-decoration: underline;\">Vorgehen:<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">1. Trainer \/ Betreuer händigt Verletztem \/ Erziehungsberechtigten den <a href=\"http:\/\/vfl-grafenwald-jugend.de\/archive\/document\/13fdf960-405b-436f-90d9-fd0473deb9dd\" target=\"_blank\" class=\"weblink\">Meldebogen<\/a> (auch in der Trainer-Datencloud zu finden) aus<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">2. Trainer \/ Betreuer informiert die Jugendleitung über den Vorfall<\/span><\/p>\n\r<p class=\"p_ARIAL11\"><span class=\"f_ARIAL11\">3. Der so genau wie möglich ausgefüllte Bogen muss unterschrieben in der Geschäftsstelle (Sensenfeld 96, 46244 Bottrop - im Jugend- und Vereinsheim) eingereicht werden.<\/span><\/p>\n\r<p><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r<p><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r<p style=\"margin: 0px 14.2500rem 0px 0px;\"><img src=\".\/images\/embim1.gif\" style=\"width:37.1875rem; height: 52.6250rem; margin:0px; border:none\" alt=\"\" \/><\/p>\n\r<p style=\"margin: 0px 14.2500rem 0px 0px;\"><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r<p style=\"margin: 0px 14.2500rem 0px 0px;\"><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r"
})
